const users = [
    {
        display_name: 'n00b01',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In ornare quam viverra orci sagittis eu volutpat. Feugiat pretium nibh ipsum consequat nisl vel pretium. Adipiscing elit ut a ',
        platforms: 'google stadia',
        lfm_in: ['dora adventures', 'apex legends', 'midnight club dub edition remix'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://media.vanityfair.com/photos/57e00bc61e9e7cc118c458c7/master/w_2560%2Cc_limit/kanye-west-sad.jpg',
        user_id: 1,
    },
    {
        display_name: 'queenCovid',
        bio: 'i love off brand doritos',
        platforms: 'gamecube',
        lfm_in: ['midnight club dub edition remix', 'naruto ultimate ninja storm 4', 'pokemon go'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://parade.com/wp-content/uploads/2019/10/taylor-swift-selena-gomez-2.jpg',
        user_id: 2,
    },
    {
        display_name: 'joe',
        bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In ornare quam viverra orci sagittis eu volutpat. Feugiat pretium nibh ipsum consequat nisl vel pretium. Adipiscing elit ut a ',
        platforms: 'xbox one',
        lfm_in: ['midnight club dub edition remix', 'naruto ultimate ninja storm 4', 'pokemon go'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://bucket.mn2s.com/wp-content/uploads/2018/10/13145038/fat-joe.png_effected.jpg',
        user_id: 3,
    },
    {
        display_name: 'nick',
        bio: 'i like cheesy poofs',
        platforms: 'playstation 2',
        lfm_in: ['dora adventures', 'apex legends', 'midnight club dub edition remix'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Nicolas_Cage_-_66%C3%A8me_Festival_de_Venise_%28Mostra%29.jpg',
        user_id: 4,
    },
    {
        display_name: 'john4134',
        bio: 'idk im bad with bios lol',
        platforms: 'playstation 4',
        lfm_in: ['midnight club dub edition remix', 'naruto ultimate ninja storm 4', 'pokemon go'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://www.biography.com/.image/t_share/MTIwNjA4NjMzNzAzNzI4NjUy/john-cena-562300-1-402.jpg',
        user_id: 5,
    },
    {
        display_name: 'john413436',
        bio: 'johns clone',
        platforms: ['PlayStation 4', 'Xbox', 'PC', 'Nintendo'],
        lfm_in: ['dora adventures', 'apex legends', 'midnight club dub edition remix'],
        genres: ['FPS', 'Adventure', 'RPG'],
        avatar: 'https://www.biography.com/.image/t_share/MTIwNjA4NjMzNzAzNzI4NjUy/john-cena-562300-1-402.jpg',
        user_id: 6,
    },
]

export default users